spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/pages
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update